[package]
name = "glbs"
version = "0.1.0"
authors = ["Arnaud Valensi <arnaud.valensi@gmail.com>"]

[dependencies]
gl = "0.6.0"
glutin = "*"
cgmath = "0.14.1"
image = "0.14.0"
floating-duration = "0.1.2"
dot_vox = "1.0.0"
